export const ADD_FAVORITE_STARSHIP = "ADD_FAVORITE_STARSHIP";
export const REMOVE_FAVORITE_STARSHIP = "REMOVE_FAVORITE_STARSHIP";
export const ADD_FETCHED_DATA = "ADD_FETCHED_DATA";
export const ADD_FETCHED_DATA_SEARCH = "ADD_FETCHED_DATA_SEARCH";
