export const ADD_FAVORITE_STARSHIP = "ADD_FAVORITE_STARSHIP";
export const REMOVE_FAVORITE_STARSHIP = "REMOVE_FAVORITE_STARSHIP";
export const ADD_FETCHED_DATA = "ADD_FETCHED_DATA";
export const ADD_FETCHED_DATA_SEARCH = "ADD_FETCHED_DATA_SEARCH";
export const ADD_FETCHED_DATA_SEARCH_PEOPLE = "ADD_FETCHED_DATA_SEARCH_PEOPLE";
export const ADD_PEOPLE_TO_STARSHIP = "ADD_PEOPLE_TO_STARSHIP";
export const REMOVE_PEOPLE_TO_STARSHIP = "REMOVE_PEOPLE_TO_STARSHIP";
